version: '3.8'

volumes:
  postgres-data:
  service-data:

services:
  service:
    image: service:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - service-data:/workspaces/go-dynamic-filters-perf
    env_file:
      - .env.local
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 20M


  db:
    image: postgres:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.local
