version: '3.8'

volumes:
  postgres-data:
  service-data:

services:
  service:
    image: service:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - service-data:/
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
