version: '3.8'

volumes:
  postgres-data:
  service-data:

services:
  service:
    image: service:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - service-data:/workspaces/go-dynamic-filters-perf
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 20M


  db:
    extends:
      file: docker-compose.dev.yaml
      service: db
