version: '3.8'

volumes:
  postgres-data: ./postgres-data
  service-data: ./service-data

services:
  service:
    image: service:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - service-data:/workspaces/go-dynamic-filters-perf
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
